# source private.env; export S3_ACCESS_KEY_ID; export S3_SECRET_ACCESS_KEY; docker-compose -f docker-compose.yml -f docker-compose.minio1.yml up
version: '3.8'

x-minio-common:
   &minio-common
   env_file:
      - private.env
      - public.env
   environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
   image: quay.io/minio/minio:latest
   command: server --console-address ":9001" /data
   healthcheck:
      test:
         [
            "CMD",
            "curl",
            "-f",
            "http://localhost:9000/minio/health/live"
         ]
      interval: 30s
      timeout: 20s
      retries: 3

services:
   app:
      depends_on:
         - db
         - minio-server

   minio1:
      <<: *minio-common
      hostname: minio1
      volumes:
         - data:/data

   minio-server:
      image: nginx:1.19.2-alpine
      hostname: minio-server
      volumes:
         - ./config/nginx1.conf:/etc/nginx/nginx.conf:ro
      ports:
         # needed to access console http://127.0.0.1:9001/login
         - "9000:9000"
         - "9001:9001"
      depends_on:
         - minio1

volumes:
   data:
