version: '3.8'

x-env-common:
   &env-common
   env_file:
      - private.env
      - public.env

services:
   app:
      <<: *env-common
      build:
         context: .
      image: phenopolis_api
      command: |
         sh -c "gunicorn -b 0.0.0.0:5000 --reload --workers=1 --threads=15 application:application"
      ports:
         - 5000:5000
      volumes:
         - ./:/app
      depends_on:
         - db
   db:
      <<: *env-common
      image: postgres:12-alpine
      volumes:
         - db:/var/lib/postgresql/data
         - ./:/app
         - ./schema/initdb.d/:/docker-entrypoint-initdb.d

   frontend:
      <<: *env-common
      tty: true # give extra colours in term log
      build:
         context: frontend
      image: phenopolis_frontend
      command: ./entrypoint.sh _redirects_docker
      ports:
         - 8888:8888 # export 8889 to avoid jupyter on 8888
      depends_on:
         - app
      volumes:
         - ./frontend/:/app
      stdin_open: true

volumes:
   db:
