# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AgeHist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _30: int=None, _35: int=None, _40: int=None, _45: int=None, _50: int=None, _55: int=None, _60: int=None, _65: int=None, _70: int=None, _75: int=None, _80: int=None, lt_30: int=None, mt_80: int=None):  # noqa: E501
        """AgeHist - a model defined in Swagger

        :param _30: The _30 of this AgeHist.  # noqa: E501
        :type _30: int
        :param _35: The _35 of this AgeHist.  # noqa: E501
        :type _35: int
        :param _40: The _40 of this AgeHist.  # noqa: E501
        :type _40: int
        :param _45: The _45 of this AgeHist.  # noqa: E501
        :type _45: int
        :param _50: The _50 of this AgeHist.  # noqa: E501
        :type _50: int
        :param _55: The _55 of this AgeHist.  # noqa: E501
        :type _55: int
        :param _60: The _60 of this AgeHist.  # noqa: E501
        :type _60: int
        :param _65: The _65 of this AgeHist.  # noqa: E501
        :type _65: int
        :param _70: The _70 of this AgeHist.  # noqa: E501
        :type _70: int
        :param _75: The _75 of this AgeHist.  # noqa: E501
        :type _75: int
        :param _80: The _80 of this AgeHist.  # noqa: E501
        :type _80: int
        :param lt_30: The lt_30 of this AgeHist.  # noqa: E501
        :type lt_30: int
        :param mt_80: The mt_80 of this AgeHist.  # noqa: E501
        :type mt_80: int
        """
        self.swagger_types = {
            '_30': int,
            '_35': int,
            '_40': int,
            '_45': int,
            '_50': int,
            '_55': int,
            '_60': int,
            '_65': int,
            '_70': int,
            '_75': int,
            '_80': int,
            'lt_30': int,
            'mt_80': int
        }

        self.attribute_map = {
            '_30': '30',
            '_35': '35',
            '_40': '40',
            '_45': '45',
            '_50': '50',
            '_55': '55',
            '_60': '60',
            '_65': '65',
            '_70': '70',
            '_75': '75',
            '_80': '80',
            'lt_30': 'lt_30',
            'mt_80': 'mt_80'
        }

        self.__30 = _30
        self.__35 = _35
        self.__40 = _40
        self.__45 = _45
        self.__50 = _50
        self.__55 = _55
        self.__60 = _60
        self.__65 = _65
        self.__70 = _70
        self.__75 = _75
        self.__80 = _80
        self._lt_30 = lt_30
        self._mt_80 = mt_80

    @classmethod
    def from_dict(cls, dikt) -> 'AgeHist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AgeHist of this AgeHist.  # noqa: E501
        :rtype: AgeHist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _30(self) -> int:
        """Gets the _30 of this AgeHist.


        :return: The _30 of this AgeHist.
        :rtype: int
        """
        return self.__30

    @_30.setter
    def _30(self, _30: int):
        """Sets the _30 of this AgeHist.


        :param _30: The _30 of this AgeHist.
        :type _30: int
        """

        self.__30 = _30

    @property
    def _35(self) -> int:
        """Gets the _35 of this AgeHist.


        :return: The _35 of this AgeHist.
        :rtype: int
        """
        return self.__35

    @_35.setter
    def _35(self, _35: int):
        """Sets the _35 of this AgeHist.


        :param _35: The _35 of this AgeHist.
        :type _35: int
        """

        self.__35 = _35

    @property
    def _40(self) -> int:
        """Gets the _40 of this AgeHist.


        :return: The _40 of this AgeHist.
        :rtype: int
        """
        return self.__40

    @_40.setter
    def _40(self, _40: int):
        """Sets the _40 of this AgeHist.


        :param _40: The _40 of this AgeHist.
        :type _40: int
        """

        self.__40 = _40

    @property
    def _45(self) -> int:
        """Gets the _45 of this AgeHist.


        :return: The _45 of this AgeHist.
        :rtype: int
        """
        return self.__45

    @_45.setter
    def _45(self, _45: int):
        """Sets the _45 of this AgeHist.


        :param _45: The _45 of this AgeHist.
        :type _45: int
        """

        self.__45 = _45

    @property
    def _50(self) -> int:
        """Gets the _50 of this AgeHist.


        :return: The _50 of this AgeHist.
        :rtype: int
        """
        return self.__50

    @_50.setter
    def _50(self, _50: int):
        """Sets the _50 of this AgeHist.


        :param _50: The _50 of this AgeHist.
        :type _50: int
        """

        self.__50 = _50

    @property
    def _55(self) -> int:
        """Gets the _55 of this AgeHist.


        :return: The _55 of this AgeHist.
        :rtype: int
        """
        return self.__55

    @_55.setter
    def _55(self, _55: int):
        """Sets the _55 of this AgeHist.


        :param _55: The _55 of this AgeHist.
        :type _55: int
        """

        self.__55 = _55

    @property
    def _60(self) -> int:
        """Gets the _60 of this AgeHist.


        :return: The _60 of this AgeHist.
        :rtype: int
        """
        return self.__60

    @_60.setter
    def _60(self, _60: int):
        """Sets the _60 of this AgeHist.


        :param _60: The _60 of this AgeHist.
        :type _60: int
        """

        self.__60 = _60

    @property
    def _65(self) -> int:
        """Gets the _65 of this AgeHist.


        :return: The _65 of this AgeHist.
        :rtype: int
        """
        return self.__65

    @_65.setter
    def _65(self, _65: int):
        """Sets the _65 of this AgeHist.


        :param _65: The _65 of this AgeHist.
        :type _65: int
        """

        self.__65 = _65

    @property
    def _70(self) -> int:
        """Gets the _70 of this AgeHist.


        :return: The _70 of this AgeHist.
        :rtype: int
        """
        return self.__70

    @_70.setter
    def _70(self, _70: int):
        """Sets the _70 of this AgeHist.


        :param _70: The _70 of this AgeHist.
        :type _70: int
        """

        self.__70 = _70

    @property
    def _75(self) -> int:
        """Gets the _75 of this AgeHist.


        :return: The _75 of this AgeHist.
        :rtype: int
        """
        return self.__75

    @_75.setter
    def _75(self, _75: int):
        """Sets the _75 of this AgeHist.


        :param _75: The _75 of this AgeHist.
        :type _75: int
        """

        self.__75 = _75

    @property
    def _80(self) -> int:
        """Gets the _80 of this AgeHist.


        :return: The _80 of this AgeHist.
        :rtype: int
        """
        return self.__80

    @_80.setter
    def _80(self, _80: int):
        """Sets the _80 of this AgeHist.


        :param _80: The _80 of this AgeHist.
        :type _80: int
        """

        self.__80 = _80

    @property
    def lt_30(self) -> int:
        """Gets the lt_30 of this AgeHist.


        :return: The lt_30 of this AgeHist.
        :rtype: int
        """
        return self._lt_30

    @lt_30.setter
    def lt_30(self, lt_30: int):
        """Sets the lt_30 of this AgeHist.


        :param lt_30: The lt_30 of this AgeHist.
        :type lt_30: int
        """

        self._lt_30 = lt_30

    @property
    def mt_80(self) -> int:
        """Gets the mt_80 of this AgeHist.


        :return: The mt_80 of this AgeHist.
        :rtype: int
        """
        return self._mt_80

    @mt_80.setter
    def mt_80(self, mt_80: int):
        """Sets the mt_80 of this AgeHist.


        :param mt_80: The mt_80 of this AgeHist.
        :type mt_80: int
        """

        self._mt_80 = mt_80
