# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.hpo import HPO  # noqa: F401,E501
from swagger_server.models.variant_basic import VariantBasic  # noqa: F401,E501
from swagger_server import util


class Gene(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, symbol: str=None, p_li: float=None, p_res: float=None, omim: List[str]=None, variants: List[VariantBasic]=None, hpo: HPO=None):  # noqa: E501
        """Gene - a model defined in Swagger

        :param id: The id of this Gene.  # noqa: E501
        :type id: str
        :param symbol: The symbol of this Gene.  # noqa: E501
        :type symbol: str
        :param p_li: The p_li of this Gene.  # noqa: E501
        :type p_li: float
        :param p_res: The p_res of this Gene.  # noqa: E501
        :type p_res: float
        :param omim: The omim of this Gene.  # noqa: E501
        :type omim: List[str]
        :param variants: The variants of this Gene.  # noqa: E501
        :type variants: List[VariantBasic]
        :param hpo: The hpo of this Gene.  # noqa: E501
        :type hpo: HPO
        """
        self.swagger_types = {
            'id': str,
            'symbol': str,
            'p_li': float,
            'p_res': float,
            'omim': List[str],
            'variants': List[VariantBasic],
            'hpo': HPO
        }

        self.attribute_map = {
            'id': 'id',
            'symbol': 'symbol',
            'p_li': 'pLI',
            'p_res': 'pRes',
            'omim': 'OMIM',
            'variants': 'variants',
            'hpo': 'HPO'
        }

        self._id = id
        self._symbol = symbol
        self._p_li = p_li
        self._p_res = p_res
        self._omim = omim
        self._variants = variants
        self._hpo = hpo

    @classmethod
    def from_dict(cls, dikt) -> 'Gene':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Gene of this Gene.  # noqa: E501
        :rtype: Gene
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Gene.


        :return: The id of this Gene.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Gene.


        :param id: The id of this Gene.
        :type id: str
        """

        self._id = id

    @property
    def symbol(self) -> str:
        """Gets the symbol of this Gene.


        :return: The symbol of this Gene.
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol: str):
        """Sets the symbol of this Gene.


        :param symbol: The symbol of this Gene.
        :type symbol: str
        """

        self._symbol = symbol

    @property
    def p_li(self) -> float:
        """Gets the p_li of this Gene.

        can be obtained from gnomAD gene constraint table  # noqa: E501

        :return: The p_li of this Gene.
        :rtype: float
        """
        return self._p_li

    @p_li.setter
    def p_li(self, p_li: float):
        """Sets the p_li of this Gene.

        can be obtained from gnomAD gene constraint table  # noqa: E501

        :param p_li: The p_li of this Gene.
        :type p_li: float
        """

        self._p_li = p_li

    @property
    def p_res(self) -> float:
        """Gets the p_res of this Gene.

        can be obtained from gnomAD gene constraint table  # noqa: E501

        :return: The p_res of this Gene.
        :rtype: float
        """
        return self._p_res

    @p_res.setter
    def p_res(self, p_res: float):
        """Sets the p_res of this Gene.

        can be obtained from gnomAD gene constraint table  # noqa: E501

        :param p_res: The p_res of this Gene.
        :type p_res: float
        """

        self._p_res = p_res

    @property
    def omim(self) -> List[str]:
        """Gets the omim of this Gene.


        :return: The omim of this Gene.
        :rtype: List[str]
        """
        return self._omim

    @omim.setter
    def omim(self, omim: List[str]):
        """Sets the omim of this Gene.


        :param omim: The omim of this Gene.
        :type omim: List[str]
        """

        self._omim = omim

    @property
    def variants(self) -> List[VariantBasic]:
        """Gets the variants of this Gene.


        :return: The variants of this Gene.
        :rtype: List[VariantBasic]
        """
        return self._variants

    @variants.setter
    def variants(self, variants: List[VariantBasic]):
        """Sets the variants of this Gene.


        :param variants: The variants of this Gene.
        :type variants: List[VariantBasic]
        """

        self._variants = variants

    @property
    def hpo(self) -> HPO:
        """Gets the hpo of this Gene.


        :return: The hpo of this Gene.
        :rtype: HPO
        """
        return self._hpo

    @hpo.setter
    def hpo(self, hpo: HPO):
        """Sets the hpo of this Gene.


        :param hpo: The hpo of this Gene.
        :type hpo: HPO
        """

        self._hpo = hpo
