# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.variant_filters import VariantFilters  # noqa: F401,E501
from swagger_server.models.variants import Variants  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, parameters: VariantFilters=None, data: Variants=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param parameters: The parameters of this InlineResponse200.  # noqa: E501
        :type parameters: VariantFilters
        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: Variants
        """
        self.swagger_types = {
            'parameters': VariantFilters,
            'data': Variants
        }

        self.attribute_map = {
            'parameters': 'parameters',
            'data': 'data'
        }

        self._parameters = parameters
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parameters(self) -> VariantFilters:
        """Gets the parameters of this InlineResponse200.


        :return: The parameters of this InlineResponse200.
        :rtype: VariantFilters
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: VariantFilters):
        """Sets the parameters of this InlineResponse200.


        :param parameters: The parameters of this InlineResponse200.
        :type parameters: VariantFilters
        """

        self._parameters = parameters

    @property
    def data(self) -> Variants:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: Variants
        """
        return self._data

    @data.setter
    def data(self, data: Variants):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: Variants
        """

        self._data = data
