# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.patient_basic_full_hpos import PatientBasicFullHpos  # noqa: F401,E501
from swagger_server.models.patient_variants import PatientVariants  # noqa: F401,E501
from swagger_server import util


class Patient(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, unrelated: bool=None, cohort: str=None, contact: str=None, hpos: List[PatientBasicFullHpos]=None, full_hpos: List[PatientBasicFullHpos]=None, variants: PatientVariants=None):  # noqa: E501
        """Patient - a model defined in Swagger

        :param id: The id of this Patient.  # noqa: E501
        :type id: str
        :param unrelated: The unrelated of this Patient.  # noqa: E501
        :type unrelated: bool
        :param cohort: The cohort of this Patient.  # noqa: E501
        :type cohort: str
        :param contact: The contact of this Patient.  # noqa: E501
        :type contact: str
        :param hpos: The hpos of this Patient.  # noqa: E501
        :type hpos: List[PatientBasicFullHpos]
        :param full_hpos: The full_hpos of this Patient.  # noqa: E501
        :type full_hpos: List[PatientBasicFullHpos]
        :param variants: The variants of this Patient.  # noqa: E501
        :type variants: PatientVariants
        """
        self.swagger_types = {
            'id': str,
            'unrelated': bool,
            'cohort': str,
            'contact': str,
            'hpos': List[PatientBasicFullHpos],
            'full_hpos': List[PatientBasicFullHpos],
            'variants': PatientVariants
        }

        self.attribute_map = {
            'id': 'id',
            'unrelated': 'unrelated',
            'cohort': 'cohort',
            'contact': 'contact',
            'hpos': 'hpos',
            'full_hpos': 'fullHpos',
            'variants': 'variants'
        }

        self._id = id
        self._unrelated = unrelated
        self._cohort = cohort
        self._contact = contact
        self._hpos = hpos
        self._full_hpos = full_hpos
        self._variants = variants

    @classmethod
    def from_dict(cls, dikt) -> 'Patient':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Patient of this Patient.  # noqa: E501
        :rtype: Patient
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Patient.


        :return: The id of this Patient.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Patient.


        :param id: The id of this Patient.
        :type id: str
        """

        self._id = id

    @property
    def unrelated(self) -> bool:
        """Gets the unrelated of this Patient.


        :return: The unrelated of this Patient.
        :rtype: bool
        """
        return self._unrelated

    @unrelated.setter
    def unrelated(self, unrelated: bool):
        """Sets the unrelated of this Patient.


        :param unrelated: The unrelated of this Patient.
        :type unrelated: bool
        """

        self._unrelated = unrelated

    @property
    def cohort(self) -> str:
        """Gets the cohort of this Patient.

        or contact name  # noqa: E501

        :return: The cohort of this Patient.
        :rtype: str
        """
        return self._cohort

    @cohort.setter
    def cohort(self, cohort: str):
        """Sets the cohort of this Patient.

        or contact name  # noqa: E501

        :param cohort: The cohort of this Patient.
        :type cohort: str
        """

        self._cohort = cohort

    @property
    def contact(self) -> str:
        """Gets the contact of this Patient.


        :return: The contact of this Patient.
        :rtype: str
        """
        return self._contact

    @contact.setter
    def contact(self, contact: str):
        """Sets the contact of this Patient.


        :param contact: The contact of this Patient.
        :type contact: str
        """

        self._contact = contact

    @property
    def hpos(self) -> List[PatientBasicFullHpos]:
        """Gets the hpos of this Patient.


        :return: The hpos of this Patient.
        :rtype: List[PatientBasicFullHpos]
        """
        return self._hpos

    @hpos.setter
    def hpos(self, hpos: List[PatientBasicFullHpos]):
        """Sets the hpos of this Patient.


        :param hpos: The hpos of this Patient.
        :type hpos: List[PatientBasicFullHpos]
        """

        self._hpos = hpos

    @property
    def full_hpos(self) -> List[PatientBasicFullHpos]:
        """Gets the full_hpos of this Patient.


        :return: The full_hpos of this Patient.
        :rtype: List[PatientBasicFullHpos]
        """
        return self._full_hpos

    @full_hpos.setter
    def full_hpos(self, full_hpos: List[PatientBasicFullHpos]):
        """Sets the full_hpos of this Patient.


        :param full_hpos: The full_hpos of this Patient.
        :type full_hpos: List[PatientBasicFullHpos]
        """

        self._full_hpos = full_hpos

    @property
    def variants(self) -> PatientVariants:
        """Gets the variants of this Patient.


        :return: The variants of this Patient.
        :rtype: PatientVariants
        """
        return self._variants

    @variants.setter
    def variants(self, variants: PatientVariants):
        """Sets the variants of this Patient.


        :param variants: The variants of this Patient.
        :type variants: PatientVariants
        """

        self._variants = variants
