# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VariantInternalAF(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, hom_af: float=None, het_af: float=None, wt_af: float=None):  # noqa: E501
        """VariantInternalAF - a model defined in Swagger

        :param hom_af: The hom_af of this VariantInternalAF.  # noqa: E501
        :type hom_af: float
        :param het_af: The het_af of this VariantInternalAF.  # noqa: E501
        :type het_af: float
        :param wt_af: The wt_af of this VariantInternalAF.  # noqa: E501
        :type wt_af: float
        """
        self.swagger_types = {
            'hom_af': float,
            'het_af': float,
            'wt_af': float
        }

        self.attribute_map = {
            'hom_af': 'hom_af',
            'het_af': 'het_af',
            'wt_af': 'wt_af'
        }

        self._hom_af = hom_af
        self._het_af = het_af
        self._wt_af = wt_af

    @classmethod
    def from_dict(cls, dikt) -> 'VariantInternalAF':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Variant_internal_AF of this VariantInternalAF.  # noqa: E501
        :rtype: VariantInternalAF
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hom_af(self) -> float:
        """Gets the hom_af of this VariantInternalAF.

        Homozygous freq in Phenopolis.  # noqa: E501

        :return: The hom_af of this VariantInternalAF.
        :rtype: float
        """
        return self._hom_af

    @hom_af.setter
    def hom_af(self, hom_af: float):
        """Sets the hom_af of this VariantInternalAF.

        Homozygous freq in Phenopolis.  # noqa: E501

        :param hom_af: The hom_af of this VariantInternalAF.
        :type hom_af: float
        """

        self._hom_af = hom_af

    @property
    def het_af(self) -> float:
        """Gets the het_af of this VariantInternalAF.


        :return: The het_af of this VariantInternalAF.
        :rtype: float
        """
        return self._het_af

    @het_af.setter
    def het_af(self, het_af: float):
        """Sets the het_af of this VariantInternalAF.


        :param het_af: The het_af of this VariantInternalAF.
        :type het_af: float
        """

        self._het_af = het_af

    @property
    def wt_af(self) -> float:
        """Gets the wt_af of this VariantInternalAF.


        :return: The wt_af of this VariantInternalAF.
        :rtype: float
        """
        return self._wt_af

    @wt_af.setter
    def wt_af(self, wt_af: float):
        """Sets the wt_af of this VariantInternalAF.


        :param wt_af: The wt_af of this VariantInternalAF.
        :type wt_af: float
        """

        self._wt_af = wt_af
