# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.variant_carriers import VariantCarriers  # noqa: F401,E501
from swagger_server.models.variant_external_af import VariantExternalAF  # noqa: F401,E501
from swagger_server.models.variant_internal_af import VariantInternalAF  # noqa: F401,E501
from swagger_server.models.variant_user_comment import VariantUserComment  # noqa: F401,E501
from swagger_server import util


class Variant(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, chromosome: str=None, position: float=None, rsid: str=None, gene: List[str]=None, external_af: VariantExternalAF=None, internal_af: VariantInternalAF=None, filter: str=None, cadd: float=None, feature_id: str=None, feature_type: str=None, hgvs_c: str=None, hgvs_p: str=None, consequence: str=None, impact: str=None, carriers: VariantCarriers=None, user_comment: VariantUserComment=None):  # noqa: E501
        """Variant - a model defined in Swagger

        :param id: The id of this Variant.  # noqa: E501
        :type id: str
        :param chromosome: The chromosome of this Variant.  # noqa: E501
        :type chromosome: str
        :param position: The position of this Variant.  # noqa: E501
        :type position: float
        :param rsid: The rsid of this Variant.  # noqa: E501
        :type rsid: str
        :param gene: The gene of this Variant.  # noqa: E501
        :type gene: List[str]
        :param external_af: The external_af of this Variant.  # noqa: E501
        :type external_af: VariantExternalAF
        :param internal_af: The internal_af of this Variant.  # noqa: E501
        :type internal_af: VariantInternalAF
        :param filter: The filter of this Variant.  # noqa: E501
        :type filter: str
        :param cadd: The cadd of this Variant.  # noqa: E501
        :type cadd: float
        :param feature_id: The feature_id of this Variant.  # noqa: E501
        :type feature_id: str
        :param feature_type: The feature_type of this Variant.  # noqa: E501
        :type feature_type: str
        :param hgvs_c: The hgvs_c of this Variant.  # noqa: E501
        :type hgvs_c: str
        :param hgvs_p: The hgvs_p of this Variant.  # noqa: E501
        :type hgvs_p: str
        :param consequence: The consequence of this Variant.  # noqa: E501
        :type consequence: str
        :param impact: The impact of this Variant.  # noqa: E501
        :type impact: str
        :param carriers: The carriers of this Variant.  # noqa: E501
        :type carriers: VariantCarriers
        :param user_comment: The user_comment of this Variant.  # noqa: E501
        :type user_comment: VariantUserComment
        """
        self.swagger_types = {
            'id': str,
            'chromosome': str,
            'position': float,
            'rsid': str,
            'gene': List[str],
            'external_af': VariantExternalAF,
            'internal_af': VariantInternalAF,
            'filter': str,
            'cadd': float,
            'feature_id': str,
            'feature_type': str,
            'hgvs_c': str,
            'hgvs_p': str,
            'consequence': str,
            'impact': str,
            'carriers': VariantCarriers,
            'user_comment': VariantUserComment
        }

        self.attribute_map = {
            'id': 'id',
            'chromosome': 'chromosome',
            'position': 'position',
            'rsid': 'rsid',
            'gene': 'gene',
            'external_af': 'external_AF',
            'internal_af': 'internal_AF',
            'filter': 'filter',
            'cadd': 'cadd',
            'feature_id': 'feature_id',
            'feature_type': 'feature_type',
            'hgvs_c': 'hgvs_c',
            'hgvs_p': 'hgvs_p',
            'consequence': 'consequence',
            'impact': 'impact',
            'carriers': 'carriers',
            'user_comment': 'userComment'
        }

        self._id = id
        self._chromosome = chromosome
        self._position = position
        self._rsid = rsid
        self._gene = gene
        self._external_af = external_af
        self._internal_af = internal_af
        self._filter = filter
        self._cadd = cadd
        self._feature_id = feature_id
        self._feature_type = feature_type
        self._hgvs_c = hgvs_c
        self._hgvs_p = hgvs_p
        self._consequence = consequence
        self._impact = impact
        self._carriers = carriers
        self._user_comment = user_comment

    @classmethod
    def from_dict(cls, dikt) -> 'Variant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Variant of this Variant.  # noqa: E501
        :rtype: Variant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Variant.


        :return: The id of this Variant.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Variant.


        :param id: The id of this Variant.
        :type id: str
        """

        self._id = id

    @property
    def chromosome(self) -> str:
        """Gets the chromosome of this Variant.


        :return: The chromosome of this Variant.
        :rtype: str
        """
        return self._chromosome

    @chromosome.setter
    def chromosome(self, chromosome: str):
        """Sets the chromosome of this Variant.


        :param chromosome: The chromosome of this Variant.
        :type chromosome: str
        """

        self._chromosome = chromosome

    @property
    def position(self) -> float:
        """Gets the position of this Variant.


        :return: The position of this Variant.
        :rtype: float
        """
        return self._position

    @position.setter
    def position(self, position: float):
        """Sets the position of this Variant.


        :param position: The position of this Variant.
        :type position: float
        """

        self._position = position

    @property
    def rsid(self) -> str:
        """Gets the rsid of this Variant.


        :return: The rsid of this Variant.
        :rtype: str
        """
        return self._rsid

    @rsid.setter
    def rsid(self, rsid: str):
        """Sets the rsid of this Variant.


        :param rsid: The rsid of this Variant.
        :type rsid: str
        """

        self._rsid = rsid

    @property
    def gene(self) -> List[str]:
        """Gets the gene of this Variant.


        :return: The gene of this Variant.
        :rtype: List[str]
        """
        return self._gene

    @gene.setter
    def gene(self, gene: List[str]):
        """Sets the gene of this Variant.


        :param gene: The gene of this Variant.
        :type gene: List[str]
        """

        self._gene = gene

    @property
    def external_af(self) -> VariantExternalAF:
        """Gets the external_af of this Variant.


        :return: The external_af of this Variant.
        :rtype: VariantExternalAF
        """
        return self._external_af

    @external_af.setter
    def external_af(self, external_af: VariantExternalAF):
        """Sets the external_af of this Variant.


        :param external_af: The external_af of this Variant.
        :type external_af: VariantExternalAF
        """

        self._external_af = external_af

    @property
    def internal_af(self) -> VariantInternalAF:
        """Gets the internal_af of this Variant.


        :return: The internal_af of this Variant.
        :rtype: VariantInternalAF
        """
        return self._internal_af

    @internal_af.setter
    def internal_af(self, internal_af: VariantInternalAF):
        """Sets the internal_af of this Variant.


        :param internal_af: The internal_af of this Variant.
        :type internal_af: VariantInternalAF
        """

        self._internal_af = internal_af

    @property
    def filter(self) -> str:
        """Gets the filter of this Variant.


        :return: The filter of this Variant.
        :rtype: str
        """
        return self._filter

    @filter.setter
    def filter(self, filter: str):
        """Sets the filter of this Variant.


        :param filter: The filter of this Variant.
        :type filter: str
        """

        self._filter = filter

    @property
    def cadd(self) -> float:
        """Gets the cadd of this Variant.


        :return: The cadd of this Variant.
        :rtype: float
        """
        return self._cadd

    @cadd.setter
    def cadd(self, cadd: float):
        """Sets the cadd of this Variant.


        :param cadd: The cadd of this Variant.
        :type cadd: float
        """

        self._cadd = cadd

    @property
    def feature_id(self) -> str:
        """Gets the feature_id of this Variant.


        :return: The feature_id of this Variant.
        :rtype: str
        """
        return self._feature_id

    @feature_id.setter
    def feature_id(self, feature_id: str):
        """Sets the feature_id of this Variant.


        :param feature_id: The feature_id of this Variant.
        :type feature_id: str
        """

        self._feature_id = feature_id

    @property
    def feature_type(self) -> str:
        """Gets the feature_type of this Variant.


        :return: The feature_type of this Variant.
        :rtype: str
        """
        return self._feature_type

    @feature_type.setter
    def feature_type(self, feature_type: str):
        """Sets the feature_type of this Variant.


        :param feature_type: The feature_type of this Variant.
        :type feature_type: str
        """

        self._feature_type = feature_type

    @property
    def hgvs_c(self) -> str:
        """Gets the hgvs_c of this Variant.


        :return: The hgvs_c of this Variant.
        :rtype: str
        """
        return self._hgvs_c

    @hgvs_c.setter
    def hgvs_c(self, hgvs_c: str):
        """Sets the hgvs_c of this Variant.


        :param hgvs_c: The hgvs_c of this Variant.
        :type hgvs_c: str
        """

        self._hgvs_c = hgvs_c

    @property
    def hgvs_p(self) -> str:
        """Gets the hgvs_p of this Variant.


        :return: The hgvs_p of this Variant.
        :rtype: str
        """
        return self._hgvs_p

    @hgvs_p.setter
    def hgvs_p(self, hgvs_p: str):
        """Sets the hgvs_p of this Variant.


        :param hgvs_p: The hgvs_p of this Variant.
        :type hgvs_p: str
        """

        self._hgvs_p = hgvs_p

    @property
    def consequence(self) -> str:
        """Gets the consequence of this Variant.


        :return: The consequence of this Variant.
        :rtype: str
        """
        return self._consequence

    @consequence.setter
    def consequence(self, consequence: str):
        """Sets the consequence of this Variant.


        :param consequence: The consequence of this Variant.
        :type consequence: str
        """

        self._consequence = consequence

    @property
    def impact(self) -> str:
        """Gets the impact of this Variant.


        :return: The impact of this Variant.
        :rtype: str
        """
        return self._impact

    @impact.setter
    def impact(self, impact: str):
        """Sets the impact of this Variant.


        :param impact: The impact of this Variant.
        :type impact: str
        """

        self._impact = impact

    @property
    def carriers(self) -> VariantCarriers:
        """Gets the carriers of this Variant.


        :return: The carriers of this Variant.
        :rtype: VariantCarriers
        """
        return self._carriers

    @carriers.setter
    def carriers(self, carriers: VariantCarriers):
        """Sets the carriers of this Variant.


        :param carriers: The carriers of this Variant.
        :type carriers: VariantCarriers
        """

        self._carriers = carriers

    @property
    def user_comment(self) -> VariantUserComment:
        """Gets the user_comment of this Variant.


        :return: The user_comment of this Variant.
        :rtype: VariantUserComment
        """
        return self._user_comment

    @user_comment.setter
    def user_comment(self, user_comment: VariantUserComment):
        """Sets the user_comment of this Variant.


        :param user_comment: The user_comment of this Variant.
        :type user_comment: VariantUserComment
        """

        self._user_comment = user_comment
