# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VariantFiltersGenotypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, patient: str=None):  # noqa: E501
        """VariantFiltersGenotypes - a model defined in Swagger

        :param patient: The patient of this VariantFiltersGenotypes.  # noqa: E501
        :type patient: str
        """
        self.swagger_types = {
            'patient': str
        }

        self.attribute_map = {
            'patient': 'patient'
        }

        self._patient = patient

    @classmethod
    def from_dict(cls, dikt) -> 'VariantFiltersGenotypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VariantFilters_genotypes of this VariantFiltersGenotypes.  # noqa: E501
        :rtype: VariantFiltersGenotypes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def patient(self) -> str:
        """Gets the patient of this VariantFiltersGenotypes.


        :return: The patient of this VariantFiltersGenotypes.
        :rtype: str
        """
        return self._patient

    @patient.setter
    def patient(self, patient: str):
        """Sets the patient of this VariantFiltersGenotypes.


        :param patient: The patient of this VariantFiltersGenotypes.
        :type patient: str
        """

        self._patient = patient
