# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VariantFiltersGnomadAf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, min: float=None, max: float=None):  # noqa: E501
        """VariantFiltersGnomadAf - a model defined in Swagger

        :param min: The min of this VariantFiltersGnomadAf.  # noqa: E501
        :type min: float
        :param max: The max of this VariantFiltersGnomadAf.  # noqa: E501
        :type max: float
        """
        self.swagger_types = {
            'min': float,
            'max': float
        }

        self.attribute_map = {
            'min': 'min',
            'max': 'max'
        }

        self._min = min
        self._max = max

    @classmethod
    def from_dict(cls, dikt) -> 'VariantFiltersGnomadAf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VariantFilters_gnomad_af of this VariantFiltersGnomadAf.  # noqa: E501
        :rtype: VariantFiltersGnomadAf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min(self) -> float:
        """Gets the min of this VariantFiltersGnomadAf.


        :return: The min of this VariantFiltersGnomadAf.
        :rtype: float
        """
        return self._min

    @min.setter
    def min(self, min: float):
        """Sets the min of this VariantFiltersGnomadAf.


        :param min: The min of this VariantFiltersGnomadAf.
        :type min: float
        """

        self._min = min

    @property
    def max(self) -> float:
        """Gets the max of this VariantFiltersGnomadAf.


        :return: The max of this VariantFiltersGnomadAf.
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max: float):
        """Sets the max of this VariantFiltersGnomadAf.


        :param max: The max of this VariantFiltersGnomadAf.
        :type max: float
        """

        self._max = max
