export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const LOGOUT = 'LOGOUT';
export const ISLOGIN_SUCCESS = 'ISLOGIN_SUCCESS';
export const ISLOGIN_FAIL = 'ISLOGIN_FAIL';
