export const CREATE_INDIVIDUA_REQUEST = 'CREATE_INDIVIDUA_REQUEST';
export const CREATE_INDIVIDUA_SUCCESS = 'CREATE_INDIVIDUA_SUCCESS';
export const CREATE_INDIVIDUA_FAIL = 'CREATE_INDIVIDUA_FAIL';

export const FETCH_INDIVIDUA_REQUEST = 'FETCH_INDIVIDUA_REQUEST';
export const FETCH_INDIVIDUA_SUCCESS = 'FETCH_INDIVIDUA_SUCCESS';
export const FETCH_INDIVIDUA_FAIL = 'FETCH_INDIVIDUA_FAIL';

export const UPDATE_INDIVIDUA_REQUEST = 'UPDATE_INDIVIDUA_REQUEST';
export const UPDATE_INDIVIDUA_SUCCESS = 'UPDATE_INDIVIDUA_SUCCESS';
export const UPDATE_INDIVIDUA_FAIL = 'UPDATE_INDIVIDUA_FAIL';
export const UPDATE_INDIVIDUA_RESET = 'UPDATE_INDIVIDUA_RESET';

export const DELETE_INDIVIDUA_REQUEST = 'DELETE_INDIVIDUA_REQUEST';
export const DELETE_INDIVIDUA_SUCCESS = 'DELETE_INDIVIDUA_SUCCESS';
export const DELETE_INDIVIDUA_FAIL = 'DELETE_INDIVIDUA_FAIL';
export const DELETE_INDIVIDUA_RESET = 'DELETE_INDIVIDUA_RESET';
