export const GET_SEARCH_AUTOCOMPLETE = 'GET_SEARCH_AUTOCOMPLETE';
export const GET_SEARCH_AUTOCOMPLETE_SUCCESS = 'GET_SEARCH_AUTOCOMPLETE_SUCCESS';
export const GET_SEARCH_AUTOCOMPLETE_FAIL = 'GET_SEARCH_AUTOCOMPLETE_FAIL';
export const GET_SEARCH_BEST = 'GET_SEARCH_BEST';
export const GET_SEARCH_BEST_SUCCESS = 'GET_SEARCH_BEST_SUCCESS';
export const GET_SEARCH_BEST_FAIL = 'GET_SEARCH_BEST_FAIL';
