export const ADD_USER_INIDIVIDUAL_REQUEST = 'ADD_USER_INIDIVIDUAL_REQUEST';
export const ADD_USER_INIDIVIDUAL_SUCCESS = 'ADD_USER_INIDIVIDUAL_SUCCESS';
export const ADD_USER_INIDIVIDUAL_FAIL = 'ADD_USER_INIDIVIDUAL_FAIL';
export const ADD_USER_INIDIVIDUAL_RESET = 'ADD_USER_INIDIVIDUAL_RESET';

export const DELETE_USER_INIDIVIDUAL_REQUEST = 'DELETE_USER_INIDIVIDUAL_REQUEST';
export const DELETE_USER_INIDIVIDUAL_SUCCESS = 'DELETE_USER_INIDIVIDUAL_SUCCESS';
export const DELETE_USER_INIDIVIDUAL_FAIL = 'DELETE_USER_INIDIVIDUAL_FAIL';
export const DELETE_USER_INIDIVIDUAL_RESET = 'DELETE_USER_INIDIVIDUAL_RESET';
