export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAIL = 'FETCH_FILES_FAIL';

export const DELETE_FILES_REQUEST = 'DELETE_FILES_REQUEST';
export const DELETE_FILES_SUCCESS = 'DELETE_FILES_SUCCESS';
export const DELETE_FILES_FAIL = 'DELETE_FILES_FAIL';

export const DOWNLOAD_FILES_REQUEST = 'DOWNLOAD_FILES_REQUEST';
export const DOWNLOAD_FILES_SUCCESS = 'DOWNLOAD_FILES_SUCCESS';
export const DOWNLOAD_FILES_FAIL = 'DOWNLOAD_FILES_FAIL';