export const INDIVIDUAL_INFO_REQUEST = 'INDIVIDUAL_INFO_REQUEST';
export const INDIVIDUAL_INFO_REQUEST_SUCCESS = 'INDIVIDUAL_INFO_REQUEST_SUCCESS';
export const INDIVIDUAL_INFO_REQUEST_FAIL = 'INDIVIDUAL_INFO_REQUEST_FAIL';
