export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_RESET = 'FETCH_USER_RESET';

export const FETCH_ONE_USER_REQUEST = 'FETCH_ONE_USER_REQUEST';
export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS';
export const FETCH_ONE_USER_FAIL = 'FETCH_ONE_USER_FAIL';
export const FETCH_ONE_USER_RESET = 'FETCH_ONE_USER_RESET';

export const FETCH_ALL_PATIENT_REQUEST = 'FETCH_ALL_PATIENT_REQUEST';
export const FETCH_ALL_PATIENT_SUCCESS = 'FETCH_ALL_PATIENT_SUCCESS';
export const FETCH_ALL_PATIENT_FAIL = 'FETCH_ALL_PATIENT_FAIL';
export const FETCH_ALL_PATIENT_RESET = 'FETCH_ALL_PATIENT_RESET';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';

export const ENABLE_USER_REQUEST = 'ENABLE_USER_REQUEST';
export const ENABLE_USER_SUCCESS = 'ENABLE_USER_SUCCESS';
export const ENABLE_USER_FAIL = 'ENABLE_USER_FAIL';
export const ENABLE_USER_RESET = 'ENABLE_USER_RESET';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET';

export const CONFIRM_REGISTRATION_REQUEST = 'CONFIRM_REGISTRATION_REQUEST';
export const CONFIRM_REGISTRATION_SUCCESS = 'CONFIRM_REGISTRATION_SUCCESS';
export const CONFIRM_REGISTRATION_FAIL = 'CONFIRM_REGISTRATION_FAIL';
export const CONFIRM_REGISTRATION_RESET = 'CONFIRM_REGISTRATION_RESET';